name: sven_hr
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version:  1.0.0+1

environment:
  sdk: ">=2.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta:
  cupertino_icons: ^1.0.0
  flutter_plugin_android_lifecycle:
  font_awesome_flutter: ^9.1.0
  smooth_star_rating: ^1.1.1
  intl: ^0.17.0
  pub_semver: ^2.0.0
  fluttertoastalert: ^1.0.3
  http: ^0.13.3
  json_annotation: ^4.0.1
  modal_progress_hud: ^0.1.3
  shared_preferences: ^2.0.6
  datetime_picker_formfield: ^2.0.0
  network_info_plus: ^1.0.2
  flutter_localizations:
    sdk: flutter
  flutter_rounded_date_picker: ^2.0.2
  image_picker: ^0.6.5
  file_picker:
  open_file: ^3.2.1
  sqflite_sqlcipher: ^2.0.0
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  connectivity: ^3.0.6
  geolocator: ^7.2.0+1
  get_mac: ^0.0.1
  sqflite_common: ^2.0.0+2
  android_intent: ^2.0.2
  searchable_dropdown: ^1.1.3
  syncfusion_flutter_charts: ^19.2.47
  downloads_path_provider: ^0.1.0
  flare_splash_screen: ^4.0.0
  flutter_vertical_marquee: ^0.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.1.0
  json_serializable: ^4.0.2
dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  analyzer:
  build_resolvers: ^1.3.10

analyzer:
  enable-experiment:
    - control-flow-collections

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/design_course/
    - assets/database/
    - assets/locale/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages